apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-processor
  namespace: platform-yunji
  labels:
    app: mysql-processor
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: mysql-processor
    spec:
      restartPolicy: Never
      nodeSelector:
        app-type: mysql-processor
      tolerations:
        - key: app-type
          value: mysql-processor
          operator: Equal
          effect: NoSchedule
      containers:
        - name: mysql-processor
          image: harbor.yunjizhizao.com/serv999/hub/izerui/mysql-processor:latest
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: config
              mountPath: /app/config.ini
              subPath: config.ini
              readOnly: true
            - name: shared-storage
              mountPath: /app/dumps
              subPath: dumps
            - name: shared-storage
              mountPath: /app/mysql
              subPath: mysql
          resources:
            requests:
              memory: "8Gi"
              cpu: "2000m"
      volumes:
        - name: config
          configMap:
            name: mysql-processor-config
        - name: shared-storage
          persistentVolumeClaim:
            claimName: mysql-processor-pvc