apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-processor-pvc
  namespace: platform-yunji
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs